"""
Reed-Solomon encoder for UDP file transfer.

Strategy: columnar erasure coding across k data chunks.
  - File is split into k equal-sized chunks (data).
  - (n-k) parity chunks are generated by applying RS to each byte column.
  - All n chunks are sent as individual UDP datagrams.
  - Any k of the n chunks are sufficient to reconstruct the file.

Packet header (36 bytes, big-endian):
  transfer_id  : 16 bytes  UUID
  block_index  :  4 bytes  position in [0, n)
  total_blocks :  4 bytes  always n
  n            :  1 byte
  k            :  1 byte
  flags        :  1 byte   bit0=IS_LAST  bit1=HAS_PADDING
  _pad         :  1 byte   reserved
  file_size    :  8 bytes  original bytes, non-zero only in block 0
"""
import math
import struct
from uuid import uuid4

from reedsolo import RSCodec

HEADER_FMT = "!16sIIBBBBQ"
HEADER_SIZE = struct.calcsize(HEADER_FMT)  # 36 bytes

_FLAG_LAST = 0x01
_FLAG_PAD = 0x02


def derive_rs_params(redundancy_level: float) -> tuple[int, int]:
    n = 32
    k = round(n * (1 - redundancy_level))
    return n, max(4, min(k, n - 1))


def encode_file(
    file_bytes: bytes,
    redundancy_level: float,
) -> tuple[list[bytes], str, int, int, int]:
    """
    Returns (packets, transfer_id_hex, n, k, chunk_size).
    Each packet = HEADER_SIZE bytes header + chunk_size bytes payload.
    """
    n, k = derive_rs_params(redundancy_level)
    nsym = n - k
    rs = RSCodec(nsym)

    transfer_id = uuid4().bytes
    file_size = len(file_bytes)

    chunk_size = max(1, math.ceil(file_size / k))
    padded_size = chunk_size * k
    padded = file_bytes + b"\x00" * (padded_size - file_size)
    has_padding = file_size < padded_size

    data_chunks = [
        bytearray(padded[i * chunk_size : (i + 1) * chunk_size]) for i in range(k)
    ]

    # Generate parity chunks column by column
    parity_chunks = [bytearray(chunk_size) for _ in range(nsym)]
    for j in range(chunk_size):
        col = bytearray(chunk[j] for chunk in data_chunks)
        enc = bytes(rs.encode(col))          # k data + nsym parity bytes
        for p in range(nsym):
            parity_chunks[p][j] = enc[k + p]

    all_chunks = data_chunks + parity_chunks  # indices 0..n-1

    packets: list[bytes] = []
    for i, chunk in enumerate(all_chunks):
        is_last = i == n - 1
        flags = (_FLAG_LAST if is_last else 0) | (_FLAG_PAD if (is_last and has_padding) else 0)
        header = struct.pack(
            HEADER_FMT,
            transfer_id,
            i,
            n,
            n, k,
            flags, 0,
            file_size,  # present in every packet so loss of block 0 is not fatal
        )
        packets.append(header + bytes(chunk))

    return packets, transfer_id.hex(), n, k, chunk_size
