"""
FastAPI dependency: extract and validate caller identity.

Dev mode  (OIDC_ENABLED=False) — no auth required; peer_id from request body.
                                   org_id fixed to "dev", all peers visible.
OIDC mode (OIDC_ENABLED=True):
  Bearer <keycloak_jwt>    → verify via JWKS; sub → peer_id,
                             realm → org_id, groups claim → groups
  Bearer <service_token>   → compare with AGENT_SERVICE_TOKEN setting;
                             treated as admin; org_id derived from OIDC_ISSUER
                             (falls back to "dev" when OIDC_ISSUER not set).
"""
import jwt
from fastapi import Header, HTTPException

from config import get_settings
from device_tokens.store import validate as validate_device_token
from .verifier import groups_from_payload, org_id_from_issuer, verify_token


class CallerInfo:
    def __init__(
        self,
        peer_id: str | None,
        is_service: bool = False,
        org_id: str = "dev",
        groups: list[str] | None = None,
    ) -> None:
        self.peer_id = peer_id
        self.is_service = is_service
        self.org_id = org_id
        self.groups: list[str] = groups or []
        admin_group = get_settings().OIDC_ADMIN_GROUP
        self.is_admin: bool = is_service or admin_group in self.groups


async def extract_auth(
    authorization: str | None = Header(default=None),
) -> CallerInfo:
    settings = get_settings()

    if not settings.OIDC_ENABLED:
        return CallerInfo(peer_id=None, is_service=False, org_id="dev")

    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(401, "Authorization header required")

    token = authorization.removeprefix("Bearer ").strip()

    # Legacy shared service token (kept for backward compat / CI scripts)
    if settings.AGENT_SERVICE_TOKEN and token == settings.AGENT_SERVICE_TOKEN:
        org = org_id_from_issuer(settings.OIDC_ISSUER) if settings.OIDC_ISSUER else "dev"
        return CallerInfo(peer_id=None, is_service=True, org_id=org)

    # Per-device token (autogenerated, revocable, stored in Redis)
    device_meta = await validate_device_token(token)
    if device_meta:
        return CallerInfo(
            peer_id=device_meta.get("peer_id") or None,
            is_service=True,
            org_id=device_meta.get("org_id", "dev"),
        )

    # OIDC JWT (human users via Keycloak)
    try:
        payload = verify_token(token)
        peer_id = payload.get("preferred_username") or payload.get("sub")
        return CallerInfo(
            peer_id=peer_id,
            is_service=False,
            org_id=org_id_from_issuer(payload.get("iss", "")),
            groups=groups_from_payload(payload),
        )
    except jwt.PyJWTError as exc:
        raise HTTPException(401, f"Invalid token: {exc}")
