# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for the RS Transfer agent — onedir mode.

a = Analysis(
    ["run.py"],
    pathex=["src", "."],
    binaries=[],
    datas=[],
    hiddenimports=[
        # uvicorn internals
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.loops.asyncio",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.h11_impl",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.protocols.websockets.websockets_impl",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "anyio",
        "anyio._backends._asyncio",
        # our modules (imported directly since src is in pathex)
        "main",
        "config",
        "server_client",
        "peers",
        "peers.router",
        "rs",
        "rs.encoder",
        "rs.decoder",
        "rs.transport",
        "rs.models",
        "files",
        "files.router",
        "transfers",
        "transfers.router",
        "transfers.models",
        "storage",
        "storage.store",
        "storage.models",
        "metrics",
        "metrics.probe",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "unittest", "pydoc", "doctest", "uvloop", "httptools"],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="rs-agent",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    optimize=2,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="rs-agent",
)
